// Code generated by "stringer -type FacilityLvl log.go"; DO NOT EDIT.

package l5424

import "strconv"

const _FacilityLvl_name = "FacilityKernelFacilityUserFacilityMailFacilitySystemDFacilitySecurityFacilitySyslogDFacilityPrinterFacilityNewsFacilityUUCPFacilityClockFacilityAuthorizationFacilityFTPFacilityNTPFacilityAuditFacilityAlertFacilityClockDFacilityLocal0FacilityLocal1FacilityLocal2FacilityLocal3FacilityLocal4FacilityLocal5FacilityLocal6FacilityLocal7"

var _FacilityLvl_index = [...]uint16{0, 14, 26, 38, 53, 69, 84, 99, 111, 123, 136, 157, 168, 179, 192, 205, 219, 233, 247, 261, 275, 289, 303, 317, 331}

func (i FacilityLvl) String() string {
	if i >= FacilityLvl(len(_FacilityLvl_index)-1) {
		return "FacilityLvl(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FacilityLvl_name[_FacilityLvl_index[i]:_FacilityLvl_index[i+1]]
}
